config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/login'

  get 'welcome/index'

  get 'about', to: 'about#show'

  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :articles
  resources :users
  resources :videos
  resources :audios

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :article_authors
    has_many :authors, :through => :article_authors

end

app/models/article_author.rb
class ArticleAuthor < ApplicationRecord
    belongs_to :author 
    belongs_to :article
end

app/models/audio.rb
class Audio < ApplicationRecord
end

app/models/author.rb
class Author < ApplicationRecord
     has_many :authored_articles, class_name: "ArticleAuthor"
     has_many :articles, :through => :authored_articles

     has_many :authored_videos, class_name: "VideoAuthor"
     has_many :videos, :through => :authored_videos
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.username = username.downcase}
    validates :username, presence: true, length: { maximum: 50 }

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/models/video.rb
class Video < ApplicationRecord
     has_many :video_authors
     has_many :authors, :through => :video_authors
end

app/models/video_author.rb
class VideoAuthor < ApplicationRecord
    belongs_to :author 
    belongs_to :video 
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def show
    end 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    include SessionsHelper

    def index
        @articles = Article.all
    end 
    
    def show 
        @article = Article.find(params[:id])
    end 

    def new
    end 

    def create
        @article = Article.new(article_params)
        @article.save

        redirect_to @article
    end 

    private 

    def article_params
        params.require(:article).permit(:title, :text)
    end 
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
    def index
        @audios = Audio.all
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    def index
    end 

    def show
        @video = Video.find(params[:id])
    end 

    def new
    end 

    def create
    end 

    def destroy
    end 

    private 

    def article_params
        params.require(:video).permit(:title, :src)
    end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @video = Video.last
    @video_authors = @video.authors
    @homepage_article = Article.last
    @article_authors = @homepage_article.authors
    @audio = Audio.last
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1 class="words-banner">Words</h1>
 

 <ul>
  <% @articles.each do |article| %>
      <li><b><%= link_to article.title, article_path(article) %></b><br>
        <%= image_tag article.image, :class => "listed-article-image" %></div>
      </li>
  <% end %>
  </ul>

app/views/articles/new.html.erb
<h1>new articles</h1>


<%= form_with scope: :users, url: users_path, local: true do |form| %>
  <p>
    <%= form.label :password %><br>
    <%= form.text_field :password %>
  </p>
 
  <p>
    <%= form.label :password_confirmation %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', welcome_index_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

app/views/users/login.html.erb
<h1>Log in</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :username %>
      <%= f.email_field :username, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

<%= link_to 'Back', welcome_index_path %>